name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy to server
        uses: easingthemes/ssh-deploy@main
        with:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          REMOTE_HOST: ${{ vars.REMOTE_HOST }}
          REMOTE_USER: ${{ vars.REMOTE_USER }}
          REMOTE_PORT: ${{ vars.REMOTE_PORT }}
          TARGET: ${{ vars.REMOTE_TARGET }}
          ARGS: "-arvhlgo --delete"
          EXCLUDE: "/site/accounts /site/sessions /site/cache"

      - name: Set SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ vars.REMOTE_HOST }} > ~/.ssh/known_hosts

      - name: Fix permissions on server
        run: |
          ssh -p ${{ vars.REMOTE_PORT }} ${{ vars.REMOTE_USER }}@${{ vars.REMOTE_HOST }}
          sudo chown -R www-data:www-data /var/www/sp-kirby
          sudo chmod -R 775 /var/www/sp-kirby
          sudo systemctl restart nginx
